---
title: "Readings"
description: |
  Human Development and Healthy Families
---

| Week | Title | Readings |
|---|-------------------------------------|-----------------------------------------------------|
| 1 | [Life Span Human Development](http://resourcelists.lib.deakin.edu.au/items/7DA3D489-977A-E8BD-646B-B084ACF5756A.html) | READ<br />Chapter 1 Understanding Life Span Human Development: Sections 1.1 (pages 3-15) and 1.2 (pages 15-20) <br /> Chapter 2 Theories of human development: Section 2.1 (pages 49-53) |
| 2 | [Life Span Human Development](http://resourcelists.lib.deakin.edu.au/items/983A3636-B31A-E986-9DE3-8CA91703BFD1.html) | READ Chapter 2 Theories of human development: Sections 2.2 (pages 54-60),<br />2.3 (pages 60-68)<br />2.5 (pages 72-78) |
| 2 | [Life Span Human Development](http://resourcelists.lib.deakin.edu.au/items/97033426-AB01-ECB8-83A3-4521240805B9.html) | READ Chapter 2 Theories of human development:<br /> Sections 2.4 (pages 68-71)<br />2.6 (pages 78-82) |
| 3 | [Life Span Human Development](http://resourcelists.lib.deakin.edu.au/items/B541BAD5-E860-CE9B-3C68-FD4E5D15F04F.html) | READ<br />Chapter 1 Understanding Life Span Human Development: Section 1.1 (pages 12-14) |
| 3 | [Studying Marriages and Families](http://resourcelists.lib.deakin.edu.au/items/2F2FD98A-2713-94F8-6A12-AE6F4CCE9A09.html) | READ Chapter Studying Marriages and Families (pages 38-54). |
| 4 | [Genes, environment and the beginnings of life](http://resourcelists.lib.deakin.edu.au/items/166947E3-B8B5-AD2C-9713-990CC24035F4.html) | READ Chapter 3 Genes, environment and the beginnings of life (pages 97-155) |
| 5 | [Life Span Human Development](http://resourcelists.lib.deakin.edu.au/items/4C0F9849-9264-3479-7EEC-B781F06737F4.html) | READ Chapter 4 Body, brain and health: Section 4.2 (pages 164-175)<br />Chapter 5 Cognitive development: Section 5.4 (pages 237-240)<br />Chapter 8 Language, literacy and learning: Section 8.2 (pages 388-398)<br />Chapter 9 Self, personality, gender and sexuality: Section 9.2 (pages 440-446)<br />Chapter 11 Emotions, attachment and social relationships: Section 11.3 (pages 562-572)|
| 5 | [Life Span Human Development](http://resourcelists.lib.deakin.edu.au/items/2E158738-95F2-8D75-26D8-FE22826A8356.html) | READ<br />Chapter 6 Sensory-perception, attention and memory: Section 6.2 (pages 274-286)<br />Chapter 7 Intelligence and creativity: Section 7.3 (pages 345-348)<br />Chapter 10 Social cognition and moral development: Section 10.3 (pages 509-512)<br />Chapter 12 Developmental psychopathology: Section 12.2 (pages 623-630)<br />Chapter 13 The final challenge: Death and dying: Section 13.3 (pages 697-698) |
| 6 | [Life Span Human Development](http://resourcelists.lib.deakin.edu.au/items/F4461CB8-1A00-8687-3665-F71F54C94567.html) | READ<br />Chapter 4 Body, brain and health: Section 4.3 (pages 176-184)<br />Chapter 5 Cognitive development: Section 5.5 Preschoolers: Symbolic thinking (pages 241-246)<br />Chapter 9 Self, personality, gender and sexuality: Section 9.3 (pages 446-456)<br />Chapter 11 Emotions, attachment and social relationships: Section 11.4 (pages 573-579) |
| 6 | [Life Span Human Development](http://resourcelists.lib.deakin.edu.au/items/8AD2022E-5CBD-4C29-B806-9AE359CFEF3B.html) | READ<br />Chapter 6 Sensory-perception, attention and memory: Section 6.3 (pages 287-298)<br />Chapter 7 Intelligence and creativity: Section 7.4 (pages 351-352)<br />Chapter 8 Language, literacy and learning: Section 8.3 (pages 398-410)<br />Chapter 10 Social cognition and moral development: Section 10.4 (pages 513-517)<br />Chapter 12 Developmental psychopathology: Section 12.3 (pages 631-639)<br />Chapter 13 The final challenge: Death and dying: Section 13.4 (pages 699-703) |
| 7 | [Life Span Human Development](http://resourcelists.lib.deakin.edu.au/items/F8D72BCA-AE56-5C9B-7972-336A7C477E39.html) | READ<br />Chapter 4 Body, brain and health: Section 4.3 (if not read in Week 6)<br />Chapter 5 Cognitive development: Section 5.5 School-age children: Logical thinking (pp. 246-248)<br />Chapter 9 Self, personality, gender and sexuality: Section 9.3 (if not read in Week 6)<br />Chapter 11 Emotions, attachment and social relationships: Section 11.4 (if not read in week 6) |
| 7 | [Life Span Human Development](http://resourcelists.lib.deakin.edu.au/items/6EC05952-B304-07D6-0CB1-DBCF233A2BA0.html) | READ<br />Chapter 6 Sensory-perception, attention and memory: Section 6.3 (if not read in Week 6)<br />Chapter 7 Intelligence and creativity: Section 7.4 (if not read in Week 6)<br />Chapter 8 Language, literacy and learning: Section 8.3 (if not read in Week 6)<br />Chapter 10 Social cognition and moral development: Section 10.4 (if not read in Week 6)<br />Chapter 12 Developmental psychopathology: Section 12.3 (if not read in Week 6)<br />Chapter 13 The final challenge: Death and dying: Section 13.4 (if not read in Week 6) |
| 8 | [Life Span Human Development](http://resourcelists.lib.deakin.edu.au/items/30A3168A-3E3B-9D06-7906-9C30C826DF8C.html) | READ Chapter 4 Body, brain and health: Section 4.4 (pages 185-195)<br />Chapter 5 Cognitive development: Section 5.6 (pages 249-255)Chapter 9 Self, personality, gender and sexuality: Section 9.4 (pages 457-465)<br />Chapter 10 Social cognition and moral development: Section 10.5 (pages 518-529)Chapter 11 Emotions, attachment and social relationships: Section 11.5 (pages 580-583) |
| 8 | [Life Span Human Development](http://resourcelists.lib.deakin.edu.au/items/DBA9251E-63AA-2D17-C59D-AE75CCBBBE06.html) | READ Chapter 6 Sensory-perception, attention and memory: Section 6.4 (pages 299-302)<br />Chapter 7 Intelligence and creativity: Section 7.5 (pages 353-354)<br />Chapter 8 Language, literacy and learning: Section 8.4 (pages 411-415)<br />Chapter 12 Developmental psychopathology: Section 12.4 (pages 640-654)<br />Chapter 13 The final challenge: Death and dying: Section 13.5 (pages 704-705) |
| 9 | [Life Span Human Development](http://resourcelists.lib.deakin.edu.au/items/AECC7D48-6B97-51FC-43E4-555D3E3C3B7A.html) | READ Chapter 9 Self, personality, gender and sexuality: Section 9.5 Eriksonian personality growth - Early adult intimacy (page 471) and Vocational identity and development - Establishing a career (pages 475-476)<br />Chapter 11 Emotions, attachment and social relationships: Section 11.6 Evolving social relationships (pages 584-585) and Family relationships - Couple relationships (pages 585-588) |
| 9 | [Life Span Human Development](http://resourcelists.lib.deakin.edu.au/items/E9E99EE3-23E2-3384-5BA2-C86B1A66A6A5.html) | READ Chapter 5 Cognitive development: Section 5.7 (pages 256-259)<br />Chapter 8 Language, literacy and learning: Section 8.5 (pages 416-420) |
| 10 | [Life Span Human Development](http://resourcelists.lib.deakin.edu.au/items/193E3219-A307-7CCF-9960-A0EDCC1E5F9B.html) | READ Chapter 4 Body, brain and health: Section 4.5 (pages 196-218)<br />Chapter 9 Self, personality, gender and sexuality: Section 9.5 Eriksonian personality growth - Midlife generativity (pages 471-472) and Vocational identity and development - The ageing worker (pages 476-477)<br />Chapter 11 Emotions, attachment and social relationships: Section 11.6 Family relationships - Adult parent-child relationships (pages 588-589) and Family relationships -Adult sibling relationships (page 589) |
| 10 | [Life Span Human Development](http://resourcelists.lib.deakin.edu.au/items/723841BA-E833-53B8-3A27-893AE6ECF310.html) | READ Chapter 12 Developmental psychopathology: Section 12.5  Depression in adulthood (pages 656-657)<br />Chapter 13 The final challenge: Death and dying: Section 13.6 Death in the family context (pages 706-712) |
11| [Life Span Human Development](http://resourcelists.lib.deakin.edu.au/items/6C153E7D-02EF-64BC-72E9-607DC4B19B6C.html) | READ Chapter 6 Sensory-perception, attention and memory: Section 6.5 (pages 303-315)<br />Chapter 9 Self, personality, gender and sexuality: Section 9.5 Eriksonian personality growth – Old-age integrity (page 472) and Vocational identity and development – Retirement (pages 477-478)<br />Chapter 11 Emotions, attachment and social relationships: Section 11.6 Grandparenthood (pages 589-590) |
| 11 | [Life Span Human Development](http://resourcelists.lib.deakin.edu.au/items/E17AA486-8057-44BA-4997-21CCB5F88718.html) | READ Chapter 12 Developmental psychopathology: Section 12.5 Ageing and dementia (pages 658-662) |