---
title: "Week 2: Theories of Human Development"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Theories {.tabset}

### Psychoanalytic



#### Freud: Psychoanalytic theory

#### Erikson: Psychosocial theory



|            | Freud's Psychosexual Stages |                                                                                                                                                                      | Erikson's Psychosocial Stages |                                                                                                                                                                                |
|:----------:|:---------------------------:|----------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-----------------------------:|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Age Range  | Stage                       | Description                                                                                                                                                          | Stage                         | Description                                                                                                                                                                    |
| Birth to 1 | Oral                        | Libido is focused on the mouth as a source of pleasure. Obtaining oral gratification from a mother figure is critical to later development.                          | Trust vs mistrust             | Infants must learn to trust their caregivers to meet their needs. Responsive parenting is critical.                                                                            |
| 1 to 3     | Anal                        | Libido is focused on the anus, and toilet training creates conflicts between the child’s biological urges and society’s demands.                                     | Autonomy vs shame and doubt   | Children must learn to be autonomous (to assert their wills and do things for themselves) or they will doubt their abilities.                                                  |
| 3 to 6     | Phallic                     | Libido centres on the genitals. Resolution of the Oedipus or the Electra complex results in identification with the same-sex parent and development of the superego. | Initiative vs guilt           | Preschoolers develop initiative by devising and carrying out bold plans, but they must learn not to impinge on the rights of others.                                           |
| 6 to 12    | Latent                      | Libido is quiet; psychic energy is invested in schoolwork and play with same-sex friends.                                                                            | Industry vs inferiority       | Children must master important social and academic skills and keep up with their peers; otherwise, they will feel inferior.                                                    |
| 12 to 20   | Genital                     | Puberty reawakens the sexual instincts as youths seek to establish mature sexual relationships and pursue the biological goal of reproduction.                       | Identity vs role confusion    | Adolescents ask who they are and must establish social and vocational identities; otherwise, they will remain confused about the roles they should play as adults.             |
| 20 to 40   |                             |                                                                                                                                                                      | Intimacy vs isolation         | Young adults seek to form a shared identity with another person, but may fear intimacy and experience loneliness and isolation.                                                |
| 40 to 65   |                             |                                                                                                                                                                      | Generativity vs stagnation    | Middle-aged adults must feel that they are producing something that will outlive them, either as parents or as workers; otherwise, they will become stagnant and self-centred. |
| 65+        |                             |                                                                                                                                                                      | Integrity vs despair          | Older adults must come to view their lives as meaningful to face death without worries and regrets.                                                                            |

#### Psychoanalytic theories: Contributions and weaknesses

### Learning

### Cognitive

## {-}

***